name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: |
          apt-get update
          apt-get install -y ruby
          gem install mustache

      - name: Creates output
        run: sh ./deploy.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_ACTIONS }}
        with:
          source-directory: "output"
          destination-github-username: "yeomin4242"
          destination-repository-name: "music-room-deployment"
          user-email: ${{ secrets.ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
